import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html lang="jp">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
