import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={
          'min-h-100vh bg-gray-900 flex justify-center items-center p-30'
        }
      >
        <div className={`max-w-xl w-100p h-300 bg-gray-800 rounded-12`}></div>
      </main>
    </>
  );
}
